sudo: false

language: scala

scala:
  - "2.12.4"
  - "2.11.11"

jdk: oraclejdk8

env:
  - TRAVIS_NODE_VERSION="7.10.1"
  - TRAVIS_NODE_VERSION="8.9.1"
  - TRAVIS_NODE_VERSION="9.2.0"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
