sudo: false

language: scala

scala:
  - "2.12.4"
  - "2.11.11"

jdk: oraclejdk8

matrix:
  include:
    - env: SBT_VERSION=0.13.16
      scala: "2.12.4"
    - env: SBT_VERSION=1.1.2
      scala: "2.12.4"

env:
  - TRAVIS_NODE_VERSION="7.10.1"
  - TRAVIS_NODE_VERSION="8.9.1"
  - TRAVIS_NODE_VERSION="9.10.1"

install:
  - source travis/setNodeVersion.sh

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - source travis/testSbtPlugin.sh
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
