sudo: required

scala:
  - "2.11.8"

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      language: scala
      before_install:
        - sudo apt-get -qq update
    - os: osx
      osx_image: xcode7.3
      before_install:
        - brew update
        - brew install sbt

cache:
  directories:
    - $HOME/.ivy2/cache

script:
  - sbt 'shoconJVM/test:compile' 'shoconJS/test:compile'
  - sbt 'shoconJVM/test:clean' 'shoconJS/test:clean'
  - sbt 'shoconJVM/test' 'shoconJS/test'
